### ISSUE TITLE
Docker CI Integration for Automated Testing and Builds

### ISSUE THREAD

**Issue by nkoik** [TvonSween/sem-one#1]
**As a** software engineer,

**I want** to integrate Docker Continuous Integration (CI) with our project,

**So that** we can automate testing, ensure code quality, and automate project builds. This integration will enable us to automatically receive reports and build the project, streamlining our development process and improving efficiency.

**Acceptance Criteria:**
- Project builds from a jar file
- Badges reflect build status
- Docker compose settings in place for db

**Tasks:**
- [x] Create token for Github login
- [x] Github Actions - set up workflow yourself
- [x] Set up Gitflow [Nikos has created necessary branches]
- [x] Add a build/licence and release badges to master. Add develop build to develop branch.
- [x] Create JAR file
- [x] Update Dockerfile to use jar
- [x] Create version tags?
- [x] Delete any old unused Docker file rebuild & commit/push code
- [x] Check status of db setup with Nikos - Db setup merged - Nikos has completed
- [x] Set up docker-compose so db and app can speak to each other?
- [x] Update github actions?

**Comment by TvonSween** [comment]
- [ ] Create token for Github login
- [ ] Github Actions - set up workflow yourself
- [x] Set up Gitflow [Nikos]
- [ ] Add a build/licence and release badges to master. Add develop build to develop branch.
- [ ] Create JAR file
- [ ] Update Dockerfile to use jar
- [ ] Create version tags?

**Comment by TvonSween** [comment]
Workflow shoud be: 
Pull the latest develop branch.
Start a new feature branch.
Once feature is finished, create JAR file.
Update and test Docker configuration with GitHub Actions.
Update feature branch with develop to ensure feature is up-to-date.
Check feature branch still works.
Merge feature branch into develop.
Repeat 2-7 until release is ready.
Merge develop branch into release and create release.
Merge release into master and develop.
